on: 
    push:
        branches: [main]  
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
 
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.logicmade.com
        username: ali@logicmade.com
        protocol: ftps
        security: loose
        password: ${{ secrets.FTP_PASSWORD }}
        timeout: 60000
        local-dir: ./
        server-dir: /test.logicmade.co.uk/
