on: 
    push:
        branches: [main]  
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
 
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    
    - name: 📂 Sync files
      uses: dennisameling/ftp-upload-action@v1.0.16
      with:
        server: ftp.logicmade.com
        username: ali@logicmade.com
        password: ${{ secrets.FTP_PASSWORD }}
        secure: false
        local_dir: ./
        server_dir: /test.logicmade.co.uk/
