on: 
    push:
        branches: [main]  
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
 
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm install --no-package-lock 
    - run: npm run build 
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.logicmade.com
        protocol: ftps
        username: ali@logicmade.com
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /test.logicmade.co.uk/
